name: fusion_esports
description: Fusion Esports Community App

publish_to: 'none'

version: 2.5.7+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.17.5
  
  # Utilities
  http: ^1.1.0
  url_launcher: ^6.2.2
  app_links: ^3.5.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0A0A0F"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#0A0A0F"
  image: "assets/icon.png"
  color_dark: "#0A0A0F"
  image_dark: "assets/icon.png"
  android_12:
    image: "assets/icon.png"
    icon_background_color: "#0A0A0F"
    image_dark: "assets/icon.png"
    icon_background_color_dark: "#0A0A0F"